"lang" = "ru"

[unique_file_id]
"терпи" = "AgADcG4AAiWZuUk"
"терплю" = "AgADw3sAAo8vuUk"
"накидывай" = "AgADumAAAk4okUk"

[categories]
good = ["хороший", "отличный", "лучший"]

[captcha_properties]
"length" = 5
"timer" = 90
"update_freq" = 10
"attempts" = 5
"bar_length" = 20

[sticker_to_sticker]
"терпи" = ["терплю"]
"терплю" = "терпи"
"накидывай" = "накидывай"

[text_to_text]
"соер {good} инженер" = ["и человек хороший"]
"декабрист {good} инженер" = "нет, соер"
"влад мишустин" = "лучший буткемп за 500к"

"таненбаума давай хули" = [
    "Что хорошо в стандартах, так это то, что у вас всегда есть из чего выбрать. \n\n - Компьютерные сети",
    "Вероятно, такая ситуация сложилась из-за ошибки одного из программистов BIOS, который писай свой шедевр на ассемблере 8088.\n\n - Архитектура компьютера",
    "В компьютерной отрасли трудно подобрать название, которое бы не выглядело смешно 30 лет спустя.\n\n - Архитектура компьютера",
    "Демон - служебная программа в некоторых операционных системах (преимущественно основанных на UNIX), работающая в фоновом режиме без непосредственного взаимодействия с пользователем.\n\n - Современные операционные системы",
    "Голодание (зависание процесса) - ситуация, когда все программы бесконечно работают, но не могут добиться никакого прогресса.\n\n - Современные операционные системы",
    "Самые быстрые блокировки - отсутствие всяких блокировок.\n\n - Современные операционные системы",
    "Рецепт - это программа (алгоритм, выраженный в некой удобной форме записи), программист - центральный процессор, ингредиенты - входные данные, процесс - действия, состоящие из чтения рецепта, выпечки...\n\n - Современные операционные системы",
    "Авторы этой книги предсказывают, что конец цивилизации произойдет в полночь 31 декабря 9999 года, когда сразу уничтожатся все программы, написанные за 8000 лет на языке COBOL.\n\n - Архитектура компьютера",
    "В компьютерной отрасли трудно подобрать название, которое бы не выглядело смешно 30 лет спустя.\n\n - Архитектура компьютера",
    "Исторически использовали и развивали искусство криптографии представители четырех профессий: военные, дипломатический корпус, люди, ведущие дневник, и любовники.",
    "Боб не знает закрытого ключа Алисы, следовательно, получить зашифрованное этим ключом сообщение он мог только от Алисы. Сидя в тюрьме за лжесвидетельство и мошенничество, Алиса сможет заняться разработкой новых интересных алгоритмов с открытым ключом.",
    "Аудио-компакт-диски содержат звуковой сигнал, оцифрованный с частотой дискретизации 44 100 Гц, в результате чего они могут хранить звуки с частотами до 22 кГц, что воспринимается как достаточно качественный звук людьми, но считается весьма низким качеством среди собак, ценящих хорошую музыку.\n\n - Компьютерные сети",
    "Проект был назван Bluetooth («Синий зуб») в честь великого короля викингов по имени Гаральд Синий Зуб II (940—981), который объединил (читай, завоевал) Данию и Норвегию. Ну да, он тоже сделал это без помощи проводов.",
    "В Unix-системах есть команда - nice, позволяющая пользователю добровольно снизить приоритет свое процесса, чтобы угодить другим пользователям, но ею никто никогда не пользуется.",
]

"посоветуй аниме" = [
    "https://myanimelist.net/anime/6213/Toaru_Kagaku_no_Railgun",
    "https://myanimelist.net/anime/8023/Toaru_Kagaku_no_Railgun__Motto_Marutto_Railgun",
    "https://myanimelist.net/anime/9047/Toaru_Kagaku_no_Railgun__Misaka-san_wa_Ima_Chuumoku_no_Mato_desu_kara",
    "https://myanimelist.net/anime/9063/Toaru_Kagaku_no_Railgun__Entenka_no_Satsuei_Model_mo_Raku_Ja_Arimasen_wa_ne",
    "https://myanimelist.net/anime/16049/Toaru_Kagaku_no_Railgun_S",
    "https://myanimelist.net/anime/19697/Toaru_Kagaku_no_Railgun_S__Motto_Marutto_Railgun",
    "https://myanimelist.net/anime/22759/Toaru_Kagaku_no_Railgun_S__Daiji_na_Koto_wa_Zenbu_Sentou_ni_Osowatta",
    "https://myanimelist.net/anime/38481/Toaru_Kagaku_no_Railgun_T",
    "https://myanimelist.net/anime/61012/Toaru_Kagaku_no_Railgun_4th_Season",
]

[text_to_sticker]
"терпи" = ["терплю"]
"терплю" = "терпи"
"накидывай накидывай" = "накидывай"

[long_message]
message_max_len = 80
long_message = [
    "Ой, длинновато... я такое не осиливаю :/",
    "Ну ты и расписался! Можно как-то короче?",
    "Я на втором слове потерялась...",
    "Это я должна всё прочитать? Серьёзно?",
    "Так, стоп. А где краткая версия для занятых?",
    "Прочитала начало… и уже устала...",
    "Может, просто скажешь, в чём суть?",
    "Если это шутка — то я её не дожила до конца.",
    "Ты уверен, что я сейчас готова к чтению романов?",
    "Лови сердечко, но читать не буду!",
    "А можно дубль покороче?",
    "Ты пока допишешь — я уже забуду, что спрашивала.",
    "Так... это сейчас что было? давай короче...",
    "У меня столько времени только на сериалы.",
    "Я аж пролистала и задумалась: это всё мне?",
    "Ты мне потом перескажешь, ладно?",
    "Если там что-то важное — сделай короткий спойлер",
    "Дай мне просто ключевое слово, я дорисую в голове",
]


[custom-titles]
adjectives = ["тушеный", "убойный", "угрюмый", "хлебный", "мертвый", "ловкий"]
nouns = ["вареник", "воробей", "олень", "тюлень", "гном", "гусь"]

[[drink-or-not]]
emoji = ["🥂","🍾","🍻","🍺"]
answer = [
    "Ну а почему бы и да?",
    "Само собой!",
    "Однозначно, сегодня тот самый день!",
    "Давай, никто не осудит.",
    "Жизнь слишком коротка для раздумий!",
]

[[drink-or-not]]
emoji = ["🥛","🧃","☕"]
answer = [
    "Не, сегодня не тот день.",
    "Лучше отложи на потом.",
    "Завтра спасибо скажешь, если не будешь.",
    "Сегодня без этого, ну его.",
    "Пусть организм отдохнёт.",
]

[[how-much-espers]]
answer = [
    "Эспер из тебя никакущий!",
    "Твои пси-волны еле шевелятся...",
    "КПД псионика как у лабораторной мыши",
    "«Научный вердикт: даже рейлган не спасёт»",
    "Ты — анти-эспер. Пси-поле обратно пропорционально."
]
emoji = [
    "(╯︵╰,) [дешевый нейросканер]",
    "(ー_ーゞ) ≡[二三二]═══════一",
    "(≖_≖ ) {сломанный пси-акселератор}",
    "(ﾉಥ益ಥ）ﾉ《Пси-глушилка v1.0》"
]

[[how-much-espers]]  
answer = [
    "Ты — ходячий генератор помех!",
    "Пси-резонанс на уровне чайника...",
    "«По шкале Рейлгана: слабый тета-ритм»",
    "Твои способности — статистическая погрешность.",
]
emoji = [
    "(＃＞＜) [Нестабильный резонатор]",
    "(~_~) ⚠︎ Railgun calibration error...",
    "(×_×) ≡[▓▓▓]═══════∈",
    "(・_・) [пси-волновой чайник]",
    "(¬_¬\") «Гарнитура не ловит пси-сигнал»"
]    

[[how-much-espers]]
answer = [
    "Непостижимая сила... почти!",
    "Квантовый пси-фазер в режиме 'чайник'!",
    "«Показатель Рейлгана: (терпимо)»",
    "Ты — живое доказательство теории пси-полей!",
    "Мозг работает, но до сингулярности далеко."
]
emoji = [
    "(＾▽＾) ⇨ [пси-импульс]",
    "(｀・ω・´) ⇄ [магноиндуктор заряжен]",
    "(ﾉ◕ヮ◕)ﾉ*:･ﾟ✧ «Эхо-винтовка онлайн»",
    "(￣ω￣) [WARNING: синхронизация мозга снижена]"
]

[[how-much-espers]]      
answer = [
    "Ты — квантовый эспер!",
    "Твои пси-волны рвут ткань реальности!",
    "Тебя можно использовать как пси-реактор!",
    "Научный феномен! Пси-поле зашкаливает!"
]
emoji = [
    "(╯✧▽✧)╯≡[RAILGUN-X]═════⊃",
    "(*≧ω≦) ✦{Пси-винтовка 𝕊-9000}",
    "☆*:.｡.o(≧▽≦)o.｡.:*☆ ↯⚛️【НейроПоток】",
    "＼(＾▽＾)／ [∞ Эспер-Катализатор]",
    "(๑•̀ㅂ•́)و✧ «Фазовый ускоритель: полная мощь»"
]
